server:
  port: 9602
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  config:
    key: enn
    ttl: 30000
logging:
  config: classpath:logback.xml
spring:
  application:
    name: yun-gateway
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
zuul:
  routes:
    advisor:
      path: /tx/advisor/**
      serviceId: ENN-ADVISOR
    channel:
      path: /tx/channel/**
      serviceId: ENN-CHANNEL
    static:
      path: /tx/xxl/xxl-job-admin/**
      url: http://10.37.147.172:9615/xxl-job-admin/
    QY-WECHAT: /qywechat/**
      #也可以使用更细的粒度 users 这个是唯一的就可以 随便起
    users:
      path: /web/**
      serviceId: SERVICE-LEFT-WEB
    #    不想向外界暴露除你配置的隐射之外的服务
    ignored-services: '*'